<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-04T16:32:42 IST" name="Default suite" finished-at="2023-06-04T16:36:36 IST" duration-ms="233968">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:Runner.TestApplication@1cf6d1be]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2023-06-04T16:32:42 IST" name="Default test" finished-at="2023-06-04T16:36:36 IST" duration-ms="233968">
      <class name="Runner.TestApplication">
        <test-method is-config="true" signature="setUpClass()[pri:0, instance:Runner.TestApplication@1cf6d1be]" started-at="2023-06-04T16:32:42 IST" name="setUpClass" finished-at="2023-06-04T16:32:44 IST" duration-ms="1775" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:Runner.TestApplication@1cf6d1be]" started-at="2023-06-04T16:32:44 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-06-04T16:36:23 IST" duration-ms="219258" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["TSR - BTII180039"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[Title of your feature]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Cancelled] but found [Create]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Cancelled] but found [Create]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepdefinitions.Request_for_financing_steps.check_the_status_its_on_cancel(Request_for_financing_steps.java:537)
at âœ½.Check the Status its on cancel(file:///C:/Users/priya/git/AZENTIO-FMS_3/Azentio_FMS_Gowtham/src/test/java/features/Request_for_Financing.feature:82)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:Runner.TestApplication@1cf6d1be]" started-at="2023-06-04T16:36:23 IST" name="tearDownClass" finished-at="2023-06-04T16:36:36 IST" duration-ms="12830" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- Runner.TestApplication -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
