<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INMUVAVD000608" failures="1" tests="2" name="Default test" time="286.41" errors="0" timestamp="2023-07-18T17:51:29 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="114.524"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="128.323">
    <failure type="java.lang.AssertionError" message="expected [1] but found [60]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [60]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepdefinitions.ApplicationFinancialFacilitySteps_608.user_validate_the_no_of_payments_input(ApplicationFinancialFacilitySteps_608.java:2692)
at âœ½.User_608 validate the No of payments input(file:///C:/Users/inindc00608/git/Sankar_FMS/FMS_SankarS2/src/test/java/features/RequestForFinancing_608.feature:49)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
